version: '3'
services:
  web:
    env_file:
      - web-variables.env
    image: "webapp:${TAG}"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
