version: "3.3"

services:
  reverse-proxy_test:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 433:433


    depends_on:
      - rfm-service
      - recomendation-service
  rfm-service:
    image: rfm-service
    build: ./Container1/.
    container_name: rfm-service
    environment:
      - APP_NAME = Bgrup_RFM
    expose: 
      - 8080
    restart: on-failure



  recomendation-service:
    image: recomendation-service
    build: ./Container2/.
    container_name: recomendation-service
    restart: on-failure
